export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const RETRIEVE_SISWA = 'RETRIEVE_SISWA';
export const RETRIEVE_DETAIL_SISWA = 'RETRIEVE_DETAIL_SISWA';
export const CREATE_SISWA = 'CREATE_SISWA';
export const UPDATE_SISWA = 'UPDATE_SISWA';
export const DELETE_SISWA = 'DELETE_SISWA';

export const RETRIEVE_GURU = 'RETRIEVE_GURU';
export const RETRIEVE_DETAIL_GURU = 'RETRIEVE_DETAIL_GURU';
export const CREATE_GURU = 'CREATE_GURU';
export const UPDATE_GURU = 'UPDATE_GURU';
export const DELETE_GURU = 'DELETE_GURU';

export const RETRIEVE_MATA_PELAJARAN = 'RETRIEVE_MATA_PELAJARAN';
export const RETRIEVE_DETAIL_MATA_PELAJARAN = 'RETRIEVE_DETAIL_MATA_PELAJARAN';
export const CREATE_MATA_PELAJARAN = 'CREATE_MATA_PELAJARAN';
export const UPDATE_MATA_PELAJARAN = 'UPDATE_MATA_PELAJARAN';
export const DELETE_MATA_PELAJARAN = 'DELETE_MATA_PELAJARAN';

export const RETRIEVE_KELAS = 'RETRIEVE_KELAS';
export const RETRIEVE_DETAIL_KELAS = 'RETRIEVE_DETAIL_KELAS';
export const CREATE_KELAS = 'CREATE_KELAS';
export const UPDATE_KELAS = 'UPDATE_KELAS';
export const DELETE_KELAS = 'DELETE_KELAS';

export const RETRIEVE_JURUSAN = 'RETRIEVE_JURUSAN';
export const RETRIEVE_DETAIL_JURUSAN = 'RETRIEVE_DETAIL_JURUSAN';
export const CREATE_JURUSAN = 'CREATE_JURUSAN';
export const UPDATE_JURUSAN = 'UPDATE_JURUSAN';
export const DELETE_JURUSAN = 'DELETE_JURUSAN';

export const RETRIEVE_TAHUN_AKADEMIK = 'RETRIEVE_TAHUN_AKADEMIK';
export const RETRIEVE_DETAIL_TAHUN_AKADEMIK = 'RETRIEVE_DETAIL_TAHUN_AKADEMIK';
export const CREATE_TAHUN_AKADEMIK = 'CREATE_TAHUN_AKADEMIK';
export const UPDATE_TAHUN_AKADEMIK = 'UPDATE_TAHUN_AKADEMIK';
export const DELETE_TAHUN_AKADEMIK = 'DELETE_TAHUN_AKADEMIK';

export const RETRIEVE_ROMBEL = 'RETRIEVE_ROMBEL';
export const RETRIEVE_DETAIL_ROMBEL = 'RETRIEVE_DETAIL_ROMBEL';
export const CREATE_ROMBEL = 'CREATE_ROMBEL';
export const UPDATE_ROMBEL = 'UPDATE_ROMBEL';
export const DELETE_ROMBEL = 'DELETE_ROMBEL';

export const RETRIEVE_KURIKULUM = 'RETRIEVE_KURIKULUM';
export const RETRIEVE_DETAIL_KURIKULUM = 'RETRIEVE_DETAIL_KURIKULUM';
export const CREATE_KURIKULUM = 'CREATE_KURIKULUM';
export const UPDATE_KURIKULUM = 'UPDATE_KURIKULUM';
export const DELETE_KURIKULUM = 'DELETE_KURIKULUM';

export const RETRIEVE_DATA_DETAIL_KURIKULUM = 'RETRIEVE_DATA_DETAIL_KURIKULUM';
export const CREATE_DETAIL_KURIKULUM = 'CREATE_DETAIL_KURIKULUM';
export const UPDATE_DETAIL_KURIKULUM = 'UPDATE_DETAIL_KURIKULUM';
export const DELETE_DETAIL_KURIKULUM = 'DELETE_DETAIL_KURIKULUM';

export const RETRIEVE_SEKOLAH = 'RETRIEVE_SEKOLAH';
export const UPDATE_SEKOLAH = 'UPDATE_SEKOLAH';

export const RETRIEVE_AGAMA = 'RETRIEVE_AGAMA';
export const RETRIEVE_JADWAL = 'RETRIEVE_JADWAL';
