export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const RETRIEVE_SISWA = 'RETRIEVE_SISWA';
export const RETRIEVE_DETAIL_SISWA = 'RETRIEVE_DETAIL_SISWA';
export const CREATE_SISWA = 'CREATE_SISWA';
export const UPDATE_SISWA = 'UPDATE_SISWA';
export const DELETE_SISWA = 'DELETE_SISWA';

export const RETRIEVE_GURU = 'RETRIEVE_GURU';
export const RETRIEVE_DETAIL_GURU = 'RETRIEVE_DETAIL_GURU';
export const CREATE_GURU = 'CREATE_GURU';
export const UPDATE_GURU = 'UPDATE_GURU';
export const DELETE_GURU = 'DELETE_GURU';

export const RETRIEVE_MATA_PELAJARAN = 'RETRIEVE_MATA_PELAJARAN';
export const RETRIEVE_DETAIL_MATA_PELAJARAN = 'RETRIEVE_DETAIL_MATA_PELAJARAN';
export const CREATE_MATA_PELAJARAN = 'CREATE_MATA_PELAJARAN';
export const UPDATE_MATA_PELAJARAN = 'UPDATE_MATA_PELAJARAN';
export const DELETE_MATA_PELAJARAN = 'DELETE_MATA_PELAJARAN';

export const RETRIEVE_SEKOLAH = 'RETRIEVE_SEKOLAH';
export const UPDATE_SEKOLAH = 'UPDATE_SEKOLAH';

export const RETRIEVE_AGAMA = 'RETRIEVE_AGAMA';
export const RETRIEVE_ROMBEL = 'RETRIEVE_ROMBEL';
